apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-ventas
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-ventas
  template:
    metadata:
      labels:
        app: back-ventas
    spec:
      containers:
      - name: back-ventas
        image: {{ECR_URL}}/back-ventas:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "db_ventas"
        - name: DB_USERNAME
          value: "user"
        - name: DB_PASSWORD
          value: "password"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-db:3306/db_ventas"
---
apiVersion: v1
kind: Service
metadata:
  name: back-ventas-svc
  namespace: devops
spec:
  selector:
    app: back-ventas
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: back-ventas-hpa
  namespace: devops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: back-ventas
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60