apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-despacho
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-despacho
  template:
    metadata:
      labels:
        app: front-despacho
    spec:
      containers:
      - name: front-despacho
        image: {{ECR_URL}}/front-despacho:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: front-despacho-svc
  namespace: devops
spec:
  type: LoadBalancer
  selector:
    app: front-despacho
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: front-despacho-hpa
  namespace: devops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: front-despacho
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 65